# Generated by Django 5.1.6 on 2025-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodel',
            name='text',
            field=models.TextField(default='asdfgf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
